package main.java.Villains;

public enum Villains {

    STARMAN, EVIL_MUSHROOM, RETRO_HIPPIE, MOBILE_SPROUT, CULTIST,
    TRICK_OR_TRICK, BRONZE_KNEECAP, TONALD_DRUMP, SMELLY_GHOST,
    ATTACK_SLUG, COIL_SNAKE, BOWSER, PORKY
}
